### PR TITLE
Adding localization to Portuguese-BR

### PR DESCRIPTION
**Pull request by marcelmendesfilho**
I have added localization to Brazillian Portuguese.

### CODE REVIEW

**Comment by HendX** [comment]
This is great! Sorry to be a pest - I was planning on setting up infrastructure today so I can easily accept strings from all languages into the app, even as the strings list evolves.

Currently there are a number of strings in the app that are no longer being used. I plan to remove those shortly.

I'll leave this pull request open so the remaining strings can be ported into the new system so up-to-date localised strings files can be generated.

**Comment by HendX** [comment]
I've set up crowdsourced translations here:

https://traceprivately.oneskyapp.com/collaboration/project?id=170066

I still need to build a workflow to incorporate this back into the code.

**Comment by marcelmendesfilho** [comment]
Just filled in the translations for Portuguese-BR on OneSkyApp project.

**Comment by HendX** [comment]
Thanks @marcelmendesfilho. These have now been integrated into the project and there is a workflow for bringing them in from OneSkey.

Because of this, I'm now going to close this pull request.

**Pull request closed without merging**
